apiVersion: cloud-build-notifiers/v1
kind: DiscordNotifier
metadata:
  name: cloud-build-discord-notifier
spec:
  notification:
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
  - name: webhook-url
    value: projects/<PROJECT_ID>/secrets/ci_cd_notification_webhook_url/versions/latest
